/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/BusinessMan.glb -o src/components/BusinessMan.jsx -r public 
*/

//BusinessMan.jsx

import { useAnimations, useGLTF, Billboard, Text } from "@react-three/drei";
import { useFrame, useGraph } from "@react-three/fiber";
import { useAtom } from "jotai";
import React, { useEffect, useMemo, useRef, useState } from "react";
import { SkeletonUtils } from 'three-stdlib'
import { charactersAtom, userAtom } from "./SocketManager";

const MOVEMENT_SPEED = 0.032;


export function BusinessMan({
  hairColor = "green",
  topColor ="pink",
  bottomColor = "brown",
  id,
  username = "Player",   // ✅ new prop for label
  isLocal = false,
  ...props
}) {
  const position = useMemo(() => props.position, []);

  const group = React.useRef()
  const { scene, animations, materials } = useGLTF('/models/BusinessMan.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  const [animation, setAnimation] = useState("CharacterArmature|Wave")
  
  useEffect(() => {
      actions[animation].reset().fadeIn(0.32).play();
      return () => actions[animation]?.fadeOut(0.32);
    }, [animation]);
  
  
    useFrame((state) => {
        if (group.current.position.distanceTo(props.position) > 0.1) {
          const direction = group.current.position
            .clone()
            .sub(props.position)
            .normalize()
            .multiplyScalar(MOVEMENT_SPEED);
          group.current.position.sub(direction);
          group.current.lookAt(props.position);
          setAnimation("CharacterArmature|Run");
        } else {
          setAnimation("CharacterArmature|Idle");
        }
        
      });
  
  return (
    <group ref={group} {...props} position= {position} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="CharacterArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh name="Suit_Legs" geometry={nodes.Suit_Legs.geometry} material={materials.Suit} skeleton={nodes.Suit_Legs.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} >
          <meshStandardMaterial color ={bottomColor}/>
          </skinnedMesh>
          <skinnedMesh name="Suit_Feet" geometry={nodes.Suit_Feet.geometry} material={materials.Black} skeleton={nodes.Suit_Feet.skeleton} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <group name="Suit_Body" position={[0, 0.007, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Suit_Body_1" geometry={nodes.Suit_Body_1.geometry} material={materials.Suit} skeleton={nodes.Suit_Body_1.skeleton} >
            <meshStandardMaterial color ={topColor}/>
            </skinnedMesh>
            
            <skinnedMesh name="Suit_Body_2" geometry={nodes.Suit_Body_2.geometry} material={materials.White} skeleton={nodes.Suit_Body_2.skeleton} />
            <skinnedMesh name="Suit_Body_3" geometry={nodes.Suit_Body_3.geometry} material={materials.Tie} skeleton={nodes.Suit_Body_3.skeleton} />
            <skinnedMesh name="Suit_Body_4" geometry={nodes.Suit_Body_4.geometry} material={materials.Skin} skeleton={nodes.Suit_Body_4.skeleton} />
          </group>
          <group name="Suit_Head" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <skinnedMesh name="Suit_Head_1" geometry={nodes.Suit_Head_1.geometry} material={materials.Skin} skeleton={nodes.Suit_Head_1.skeleton} />
            <skinnedMesh name="Suit_Head_2" geometry={nodes.Suit_Head_2.geometry} material={materials.Hair} skeleton={nodes.Suit_Head_2.skeleton} >
              <meshStandardMaterial color ={hairColor}/>
              </skinnedMesh>
            <skinnedMesh name="Suit_Head_3" geometry={nodes.Suit_Head_3.geometry} material={materials.Eyebrows} skeleton={nodes.Suit_Head_3.skeleton} />
            <skinnedMesh name="Suit_Head_4" geometry={nodes.Suit_Head_4.geometry} material={materials.Eye} skeleton={nodes.Suit_Head_4.skeleton} />
          </group>
        </group>
      </group>

      {/* ✅ Username Billboard */}
            <Billboard position={[0, 2.2, 0]}>
              <Text
                fontSize={0.2}
                color="black"
                anchorX="center"
                anchorY="middle"
                outlineWidth={0.03}
                outlineColor="white"
              >
                {username}
              </Text>
            </Billboard>
    </group>
  )
}

useGLTF.preload('/models/BusinessMan.glb')
